### ISSUE TITLE
Explorer frontend throwing "Internal server error"

### ISSUE THREAD

**Issue by mieubrisse** [near/near-explorer#1030]
I'm using the latest Docker images and the Explorer frontend will come up but accessing it throws an internal server error. The container logs are:
```
> near-explorer-frontend@0.0.1 start

> dotenv -c -e ../frontend.env -- next start


ready - started server on 0.0.0.0:3000, url: http://localhost:3000

warn  - You have enabled experimental feature(s).

warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use them at your own risk.


TypeError: Cannot read property '0' of undefined

    at getNearNetworkName (/near-explorer/frontend/.next/server/chunks/210.js:63:36)

    at Object.App.getInitialProps (/near-explorer/frontend/.next/server/pages/_app.js:1979:99)

TypeError: Cannot read property '0' of undefined

    at getNearNetworkName (/near-explorer/frontend/.next/server/chunks/210.js:63:36)

    at Object.App.getInitialProps (/near-explorer/frontend/.next/server/pages/_app.js:1979:99)

TypeError: Cannot read property '0' of undefined

    at getNearNetworkName (/near-explorer/frontend/.next/server/chunks/210.js:63:36)

    at Object.App.getInitialProps (/near-explorer/frontend/.next/server/pages/_app.js:1979:99)
```

I'm not sure why it's throwing this, as my envvars contain a NETWORK_NAME value:
```
                "NEAR_EXPLORER_CONFIG__NETWORK_NAME=localnet",
                "NEAR_EXPLORER_CONFIG__BACKEND_SSR__HOSTS__GUILDNET=explorer-backend",
                "NEAR_EXPLORER_CONFIG__BACKEND_SSR__HOSTS__MAINNET=explorer-backend",
                "NEAR_EXPLORER_CONFIG__BACKEND_SSR__HOSTS__TESTNET=explorer-backend",
                "NEAR_EXPLORER_CONFIG__BACKEND_SSR__SECURE=false",
                "NEAR_EXPLORER_CONFIG__BACKEND__HOSTS__GUILDNET=127.0.0.1",
                "NEAR_EXPLORER_CONFIG__BACKEND__HOSTS__TESTNET=127.0.0.1",
                "NEAR_EXPLORER_CONFIG__BACKEND__SECURE=false",
                "NEAR_EXPLORER_CONFIG__BACKEND_SSR__PORT=8080",
                "NEAR_EXPLORER_CONFIG__BACKEND__HOSTS__MAINNET=127.0.0.1",
                "NEAR_EXPLORER_CONFIG__BACKEND__PORT=49970",
                "PORT=3000",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "VERSION=v16.4.2",
                "NPM_VERSION=7",
                "YARN_VERSION=v1.22.10",
                "HOME=/tmp"
```
```

**Comment by luixo** [comment]
We can use a message for that.

**Comment by luixo** [comment]
Actually, we have a message.
But we didn't throw it because of a bug: https://github.com/near/near-explorer/commit/924c8320b6a311b8d17f9a29bcd581958258dd73
