### ISSUE TITLE
Public access to the telemetry database returns permission denied

### ISSUE THREAD

**Issue by frol** [near/near-explorer#775]
When I run `npm run start:mainnet-with-indexer` locally and use the default telemetry endpoint, it gives me permission error:

```
Regular network info publishing crashed due to: DatabaseError [SequelizeDatabaseError]: permission denied for table nodes
    at Query.formatError (/home/frol/projects/near.ai/near-explorer/backend/node_modules/sequelize/lib/dialects/postgres/query.js:366:16)
    at /home/frol/projects/near.ai/near-explorer/backend/node_modules/sequelize/lib/dialects/postgres/query.js:72:18
    at tryCatcher (/home/frol/projects/near.ai/near-explorer/backend/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/frol/projects/near.ai/near-explorer/backend/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/frol/projects/near.ai/near-explorer/backend/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/frol/projects/near.ai/near-explorer/backend/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/frol/projects/near.ai/near-explorer/backend/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/home/frol/projects/near.ai/near-explorer/backend/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/frol/projects/near.ai/near-explorer/backend/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/frol/projects/near.ai/near-explorer/backend/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/frol/projects/near.ai/near-explorer/backend/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (node:internal/timers:464:21) {
  parent: error: permission denied for table nodes
      at Parser.parseErrorMessage (/home/frol/projects/near.ai/near-explorer/backend/node_modules/pg-protocol/dist/parser.js:287:98)
      at Parser.handlePacket (/home/frol/projects/near.ai/near-explorer/backend/node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (/home/frol/projects/near.ai/near-explorer/backend/node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (/home/frol/projects/near.ai/near-explorer/backend/node_modules/pg-protocol/dist/index.js:11:42)
      at Socket.emit (node:events:390:28)
      at addChunk (node:internal/streams/readable:315:12)
      at readableAddChunk (node:internal/streams/readable:289:9)
      at Socket.Readable.push (node:internal/streams/readable:228:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:199:23) {
    length: 93,
    severity: 'ERROR',
    code: '42501',
    detail: undefined,
    hint: undefined,
    position: undefined,
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'aclchk.c',
    line: '3466',
    routine: 'aclcheck_error',
    sql: 'SELECT ip_address, account_id, node_id,\n' +
      '        last_seen, last_height, status,\n' +
      '        agent_name, agent_version, agent_build,\n' +
      '        latitude, longitude, city\n' +
      '      FROM nodes\n' +
      "      WHERE account_id IN ('01node.poolv1.near', '08investinwomen_runbybisontrails.poolv1.near', 'abl_pool.poolv1.near', 'accomplice.poolv1.near', 'anonymous.poolv1.near', 'appload.poolv1.near', 'astro-stakers.poolv1.near', 'audit_one.poolv1.near', 'aurora.poolv1.near', 'baziliknear.poolv1.near', 'binancestaking.poolv1.near', 'bisontrails.poolv1.near', 'blockdaemon.poolv1.near', 'buildlinks.poolv1.near', 'chorusone.poolv1.near', 'continue.poolv1.near', 'cryptium.poolv1.near', 'cryptotribe.poolv1.near', 'd1.poolv1.near', 'dokiacapital.poolv1.near', 'dragonfly.poolv1.near', 'dsrvlabs.poolv1.near', 'electric.poolv1.near', 'epic.poolv1.near', 'erm.poolv1.near', 'everstake.poolv1.near', 'figment.poolv1.near', 'finoa.poolv1.near', 'fish.poolv1.near', 'foundry.poolv1.near', 'fresh.poolv1.near', 'hashquark.poolv1.near', 'hb436_pool.poolv1.near', 'ideocolabventures.poolv1.near', 'inotel.poolv1.near', 'jazza.poolv1.near', 'legends.poolv1.near', 'lunanova.poolv1.near', 'lux.poolv1.near', 'magic.poolv1.near', 'masternode24.poolv1.near', 'moonlet.poolv1.near', 'nc2.poolv1.near', 'nearcrowd.poolv1.near', 'nearfans.poolv1.near', 'nodeasy.poolv1.near', 'northernlights.poolv1.near', 'openshards.poolv1.near', 'p2p-org.poolv1.near', 'rekt.poolv1.near', 'sharpdarts.poolv1.near', 'smart-stake.poolv1.near', 'staked.poolv1.near', 'stakesabai.poolv1.near', 'stakin.poolv1.near', 'stardust.poolv1.near', 'tottenham_hotspur.poolv1.near', 'zavodil.poolv1.near', 'zkv_staketosupportprivacy.poolv1.near', 'galaxydigital.poolv1.near', 'sparkpool.poolv1.near', 'cypherhunter.poolv1.near', '08bisontrails_investinwomen.poolv1.near', 'infinite.poolv1.near', 'cryptosolutions.poolv1.near', 'staking4all.poolv1.near', 'a1in-miningpond.poolv1.near', 'steak.poolv1.near', 'binnostake-pool.poolv1.near', 'okexpool.poolv1.near', 'lunarpulse.poolv1.near', 'genesislab.poolv1.near', 'kryptovlada-pool.poolv1.near', 'wetez.poolv1.near', '01stake.poolv1.near', 'near4u.poolv1.near', 'tribe.poolv1.near', 'jubi.poolv1.near', 'anonstake.poolv1.near', 'harry_kane.poolv1.near', 'near8888.poolv1.near', 'swiss-staking.poolv1.near', 'ashert.poolv1.near', 'rocknroll.poolv1.near', 'certusone.poolv1.near', 'huobipool.poolv1.near', 'stakefish.poolv1.near', 'johnsmith.poolv1.near', 'bobby.poolv1.near', 'majlovesreg.poolv1.near', '00agent.poolv1.near', 'alex.poolv1.near', 'blockops.poolv1.near', 'nortwhale.poolv1.near', 'chainworks.poolv1.near', 'thepassivetrust.poolv1.near', 'sphere.poolv1.near', 'mantradao.poolv1.near', 'hotbitstake.poolv1.near', 'dialecticstake.poolv1.near', 'kukulastake1.poolv1.near', 'zpool.poolv1.near', 'neardublin.poolv1.near', 'yiqi233.poolv1.near', 'miningpond_asia_jp.poolv1.near', 'iosgvc.poolv1.near', 'trillian.poolv1.near', 'sweden.poolv1.near', 'miningpond_asia_in.poolv1.near', 'artemis.poolv1.near', 'lowfeevalidation.poolv1.near', 'bizi.poolv1.near', 'easy2stake.poolv1.near', 'rioblocks.poolv1.near', 'htbstake.poolv1.near', 'link2.poolv1.near', 'gr_staking01.poolv1.near', 'agnico-1.poolv1.near', 'metaops.poolv1.near', 'rockx.poolv1.near', 'doghouse.poolv1.near', 'k300ventures.poolv1.near', 'bisontrails2.poolv1.near', 'dexagon.poolv1.near', 'onlygainz.poolv1.near', 'spectrum.poolv1.near', 'pathrocknetwork.poolv1.near', 'validatrium.poolv1.near', 'nemo.poolv1.near', 'bloclick.poolv1.near', 'gpvalidator.poolv1.near', 'ivzor.poolv1.near', 'stakingcabin.poolv1.near', 'cryptoblossom.poolv1.near', 'stakely_io.poolv1.near', 'cryptostore.poolv1.near', 'kromer.poolv1.near', 'raynetwork.poolv1.near', 'hsykj.poolv1.near', 'x50capital.poolv1.near', 'cryptogarik.poolv1.near', 'doubletop.poolv1.near', 'incrypted.poolv1.near', 'optimusvalidatornetwork.poolv1.near', 'al3c5.poolv1.near', 'main.poolv1.near', 'latenthero.poolv1.near', '0xgenesisblock.poolv1.near', 'ni.poolv1.near', 'staking-power.poolv1.near', 'lavenderfive.poolv1.near', 'basilisk-stake.poolv1.near', '1x2.poolv1.near')",
    parameters: undefined
  }
```

We should make sure that the credentials allow read access to the data (no write access).

**Comment by telezhnaya** [comment]
I forgot to run `alter default privileges`, sorry
For the history: https://github.com/near/near-indexer-for-explorer/blob/master/migrations/2021-06-09-102523_grant_select_on_new_tables/up.sql

It was also the issue for Analytics DB. 
Fixed it for 4 DBs: Analytics (mainnet, testnet), Telemetry (mainnet, testnet)
